---
title: "Train-Test-Split"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r}
dataset = read.csv(file='Data.csv')
dataset
```
```{r}
dataset$Age = ifelse(is.na(dataset$Age),
                     ave(dataset$Age, FUN = function(x) mean(x,na.rm = TRUE)),
                     dataset$Age)
dataset
```
```{r}
dataset$Salary = ifelse(is.na(dataset$Salary),
                     ave(dataset$Salary, FUN = function(x) mean(x,na.rm= TRUE)),
                     dataset$Salary)
dataset
```


```{r}
#hot encoding
library(dummies)
df <- dummy.data.frame(dataset, names=c("Country"), sep="_")
df
```




```{r}
# label encoding
dataset$Country = factor(dataset$Country,
                         levels = c('France','Spain','Germany'),
                         labels = c(1,2,3))
dataset
```


```{r}
dataset$Purchased = factor(dataset$Purchased,
                         levels = c('No','Yes'),
                         labels = c(0,1))
dataset
```


```{r}
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.8)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

# Feature Scaling
# training_set = scale(training_set)
# test_set = scale(test_set)

```
```{r}
split
```



```{r}
training_set
```

```{r}
test_set
```














